version: "3.9"
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_stack:
    image: redis/redis-stack
    container_name: redis_stack
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_stack_volume_data:/db

volumes:
  redis_volume_data:
  redis_stack_volume_data: